import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const DMsans = localFont({
  src: "./fonts/DMSans.ttf",
  variable: "--font-DMSans",
  weight: "100 300 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMsans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
